### ISSUE TITLE
Posted scores higher than local

### ISSUE THREAD

**Issue by Ehatanai** [Umbranoxio/ScoreSaber#3]
Went through and replayed most of the songs...  They seem to be okay now?

![whatyouknow](https://user-images.githubusercontent.com/40965963/42483629-4118eada-83b4-11e8-8db6-ed5fe766e67d.png)
![burn](https://user-images.githubusercontent.com/40965963/42483630-412a2188-83b4-11e8-8616-511dd7438307.png)
![midnightcity](https://user-images.githubusercontent.com/40965963/42483631-413faee0-83b4-11e8-83b1-103740a337d8.png)
![neversleepalone](https://user-images.githubusercontent.com/40965963/42483632-4151c01c-83b4-11e8-9584-61af07639885.png)
![polishgirl](https://user-images.githubusercontent.com/40965963/42483633-41647a2c-83b4-11e8-94ff-f9ecb6869acd.png)
![uptownfunk](https://user-images.githubusercontent.com/40965963/42483634-4178b050-83b4-11e8-9118-4cd6a2cdac9f.png)

==================================

This happens sporadically...

I had been manually adding songs (without the BeatSaverDownloader and UnofficialLeaderBoardPlugin dlls) for a while and just tried this out over the weekend.  The scores should only be submitted on song completion, right?

Last weekend I went through and reinstalled windows but never copied over my BeatSaber preferences/saves, so I did see discrepancies between the local and leaderboard scores for the original songs.  I didn't have the unofficial leader board plugin installed before I wiped my machine, so none of these scores could have been committed pre windows install.

![desktop screenshot 2018 07 08 - 14 50 37 24](https://user-images.githubusercontent.com/40965963/42423401-22659d36-82bf-11e8-81f8-e243cbfa9b0e.png)
![desktop screenshot 2018 07 08 - 14 46 41 41](https://user-images.githubusercontent.com/40965963/42423402-2277c678-82bf-11e8-866f-1b6ce4735d32.png)
![desktop screenshot 2018 07 08 - 14 48 22 86](https://user-images.githubusercontent.com/40965963/42423403-228aa770-82bf-11e8-8536-f3a5485e806a.png)
![desktop screenshot 2018 07 08 - 14 48 35 30](https://user-images.githubusercontent.com/40965963/42423404-229a55a8-82bf-11e8-9723-b2a7bf0cd95b.png)
![desktop screenshot 2018 07 08 - 14 49 02 93](https://user-images.githubusercontent.com/40965963/42423405-22ab2ed2-82bf-11e8-8b44-d9206daf729e.png)
![desktop screenshot 2018 07 08 - 14 50 20 92](https://user-images.githubusercontent.com/40965963/42423406-22bb2882-82bf-11e8-8a70-04c5567edc52.png)
![desktop screenshot 2018 07 08 - 14 50 27 99](https://user-images.githubusercontent.com/40965963/42423407-22ca9b0a-82bf-11e8-943e-05d97c352046.png)

**Comment by Umbranoxio** [comment]
This bug has been fixed.
