### ISSUE TITLE
Missed files in project

### ISSUE THREAD

**Issue by ArenaSpaceDev** [Umbranoxio/ScoreSaber#4]
I am trying to add some features to project, but I can't build the project, cause of missed files. Where can I find SteamPlatformLeaderboardsHandler and LeaderboardsModel?

**Comment by Umbranoxio** [comment]
The current head version of this repo is outdated, I'll commit the latest working version some time today. Than you can update.

**Comment by ArenaSpaceDev** [comment]
Thanks, but I still can't find PlatformLeaderboardsModel. Can you tell me in which library is it or what class?
